apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shukra-living
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: final_9_v7_shukra_livings_web_app_sprint_3-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://localhost:30011"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
